### ISSUE TITLE
XCORE AI / FS device will not enumerate on a specific Hub device

### ISSUE THREAD

**Issue by ed-xmos** [xmos/lib_xud#124]
When developing the 3610 I found that one specific hub (USB C -> 3 x USB A) would not enumerate the 3610. Other hubs were fine and did enumerate the device.  Also, an XTAG 4 does enumerate OK on it. The hub in question is [this one](https://www.amazon.co.uk/LENTION-Compatible-Thunderbolt-ChromeBook-Connecting/dp/B01N0406E8/ref=asc_df_B01N0406E8/?tag=googshopuk-21&linkCode=df0&hvadid=309968313994&hvpos=&hvnetw=g&hvrand=2313672188034057710&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=1007173&hvtargid=pla-332054489724&psc=1): which is a Lention 4 in one hub.

The 3610 UA build can be found here: http://srv-bri-jcim0:8080/blue/organizations/jenkins/XMOS%2Fsw_xvf3610/detail/feature%2Freinstate_ua/9/pipeline

Here's a screenshot of the descriptor.
![Screenshot 2021-04-07 at 11 29 47](https://user-images.githubusercontent.com/625517/113853035-1c8f3280-9795-11eb-95c8-d60ca8614954.png)

The device gets stuck at set address. This is never received and acted upon by the 3610  device.

Here is the non working trace. You can see it get stuck at set address:

![non working hub example](https://user-images.githubusercontent.com/625517/113853494-a212e280-9795-11eb-887b-f4af2506c0b9.png)

This is it working on different hubs:

![working hub example](https://user-images.githubusercontent.com/625517/113853445-91626c80-9795-11eb-86ba-011d7a8a09df.png)

Note that currently I am using a version of DEV/XS3 merged into develop on lib_xua to satisfy the needs of the build deps. As soon as there is an official lib_xud with XS3 support I suggest I retry..

**Comment by xross** [comment]
Potentially fixed in #157

**Comment by xross** [comment]
> Potentially fixed in #157

This did not resolve issue. I had a call with @ed-xmos and suggested some debug options, CRC check disabling etc

**Comment by xross** [comment]
Out of interest I have run "smoke" tests (HS only) @540MHz and some tests do fail (all pass at 600MHz):

=============================================================================== short test summary info ===============================================================================
FAILED test_bulk_tx_badack.py::test_RunUsbSession[xs3-1-1-HS-6-600] - assert False
FAILED test_bulk_tx_basic_noack.py::test_RunUsbSession[xs3-1-1-HS-6-600] - assert False
FAILED test_control_basic_get.py::test_RunUsbSession[xs3-0-1-HS-6-600] - assert False
FAILED test_control_basic_set.py::test_RunUsbSession[xs3-0-1-HS-6-600] - assert False
FAILED test_ping_stall.py::test_RunUsbSession[xs3-1-1-HS-6-600] - assert False
FAILED test_stall_control.py::test_RunUsbSession[xs3-0-1-HS-6-600] - assert False
================================================================= 6 failed, 22 passed, 2 xfailed in 794.68s (0:13:14)

Note, this is with 8 cores running in total (all fast mode enabled)

**Comment by ed-xmos** [comment]
Here are the results for HS so far. My summary for settings would be:
500MHz - 1 0 1 1
600MHz - 0 0 0 0 or possibly 0 0 0 1

Worryingly the 1 1 1 1 setting did not allow my 3610_UA to enumerate on NUC4 in the office so that is an issue.

@xross This is taking a lot of time now and I need to revert to getting the 3610 tests passing ready for release. I spoke briefly with Simon about this to ask what timing should be and we concluded that we need to discuss this in a meeting. I'll leave that to you organise.

[summary_500.txt](https://github.com/xmos/lib_xud/files/6829366/summary_500.txt)
[summary_600.txt](https://github.com/xmos/lib_xud/files/6829367/summary_600.txt)

**Comment by xross** [comment]
Concerned these are quite different from the current settings!

**Comment by ed-xmos** [comment]
OK, I tried the HID example, except this time with the following setup lines BEFORE XUD was called, mimicking the 3610_UA app:
#define CORE_TO_REF_CLK_RATIO (5 - 1)  //108.333 MHz
#define PLL_NOM  0xC0865511 // 540.667 MHz (540.667 / 176 = 3.07196 MHz (~3.072 MHz))

write_sswitch_reg(get_tile_id(tile[0]), XS1_SSWITCH_REF_CLK_DIVIDER_NUM, CORE_TO_REF_CLK_RATIO);
write_sswitch_reg(get_tile_id(tile[0]), XS1_SSWITCH_PLL_CTL_NUM, PLL_NOM);

Writing the PLL_CTL register to PLL_NOM kills XUD. I do not understand why because it just sets a core clock to 540.66MHz. It means the ref clk is 108.3333MHz - could this be an issue?

**Comment by ed-xmos** [comment]
I am fairly sure now that the core clock and delays are a red herring. See: https://github.com/xmos/lib_xud/issues/244

**Comment by xross** [comment]
Superseded by #244. Closing.
