### ISSUE TITLE
Read Me files not compliant wiith publication guidelines

### ISSUE THREAD

**Issue by mbanth** [xmos/lib_xud#130]
Several Application Note README.rst files include the `.. version::` xdoc directive:

- AN00124 CDC VCOM Class,
- AN00125 Mass Storage Class,
- AN00126 Printer Class,
- AN00127 Video Class,
- AN00131 CDC EDC Class,
- AN00132 Image Class (2 instances),
- AN00135 Test and Measurement Class (2 instances), and
- AN00136 Vendor Specific (2 instances).

The Read Me files in the `__app_tests` directory appear incomplete.  The Read Me file in the `tests` directory appears to contain only internal notes.

**Comment by xross** [comment]
All checks now pass.
