### ISSUE TITLE
test_sof_badcrc passes but should fail

### ISSUE THREAD

**Issue by xross** [xmos/lib_xud#182]
test_sof_badcrc passes but should fail

Running with -s shows the bad output.

**Comment by kevinyeungxmos** [comment]
see pr #187

**Comment by xross** [comment]
PR resolves the issue with test_sof_badcrc being marked fail. However, @kevinyeungxmos reports that tests that are marked xfail are now marked fail.

**Comment by xross** [comment]
@kevinyeungxmos this all seems to work fine for me?

**Comment by xross** [comment]
Fixed in #195
