### ISSUE TITLE
USB comms broken by commit Opts to XUD_Token_In_DI. Speed improvements to stall handling 933dda1 

### ISSUE THREAD

**Issue by DaveAtkinsonXMOS** [xmos/lib_xud#227]
The two lib_xud example tested (AN00124 and AN00129) work up to this [commit](https://github.com/xmos/lib_xud/commit/933dda1c1975a09871bc52813de10078295219b3), and then fail afterwards.

**Comment by DaveAtkinsonXMOS** [comment]
Here is a Total Phase Data Center trace from a Beagle, xcore.ai running AN00129 and failing.
[AN000129 Linux Failure xcore.ai.tdc.zip](https://github.com/xmos/lib_xud/files/6800447/AN000129.Linux.Failure.xcore.ai.tdc.zip)

**Comment by xross** [comment]
It looks like after a EP0 request that is halted (Set Idle) the IN Ep0 never seems to be marked ready again (NAKs forever)

**Comment by xross** [comment]
The spec states that an EP that receives a SETUP request should be un-stalled. These changes break this functionality
