### ISSUE TITLE
Remove Pyxsim code from tests and use test_support repo.

### ISSUE THREAD

**Issue by DaveAtkinsonXMOS** [xmos/lib_xud#262]
The Pyxsim code has been refactored into a new repo. We should be using that, and remove it from here.

**Comment by DaveAtkinsonXMOS** [comment]
In order to do that, can we decide how that repo is supposed to be used?

**Comment by kevinyeungxmos** [comment]
To use test_support:
run  build.pl in test_support before testing

**Comment by xross** [comment]
This appear to be somewhat addressed in PR #242. However it is currently marked DO NOT MERGE and has some conflicts

**Comment by xross** [comment]
Done
