### ISSUE TITLE
Port latest public USB Audio release to use lib_xud

### ISSUE THREAD

**Issue by xross** [xmos/lib_xud#264]
- Port sw_usb_audio 6.15.2 to use lib_xud
- Provide customer facing documentation/support

**Comment by xross** [comment]
This has been completed.

**Comment by syrykh** [comment]
Hi @xross,
> Port sw_usb_audio 6.15.2 to use lib_xud

Is it possible to get fresh ported version? Thanks in advance!

**Comment by xross** [comment]
> Hi @xross,
> 
> > Port sw_usb_audio 6.15.2 to use lib_xud
> 
> Is it possible to get fresh ported version? Thanks in advance!

yes, please contact support@xmos.com
