### ISSUE TITLE
Cannot run tests due to xcov addtions

### ISSUE THREAD

**Issue by xross** [xmos/lib_xud#287]
======================================================================== ERRORS =========================================================================
________________________________________________ ERROR at setup of test_RunUsbSession[xs3-1-1-HS-4-600] _________________________________________________
file /Users/ross/sandboxes/sb_xud_view2/lib_xud/tests/conftest.py, line 120
  def test_RunUsbSession(
E       fixture 'xcov' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, copy_xn_files, doctest_namespace, extra, include_metadata_in_junit_xml, metadata, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, test_address, test_arch, test_bus_speed, test_dummy_threads, test_ep, test_file, test_session, testrun_uid, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, worker_id, xcoverage_combination
>       use 'pytest --fixtures [testpath]' for help on them.

**Comment by kevinyeungxmos** [comment]
Set env first. In infr_scripts_pl:
`source ./SetupEnv`
Then, run Build.pl in test_support:
`./Build.pl build install`

**Comment by xross** [comment]
I have made a change such that xcov is not a fixture but in the env (matching the enabletracing option)
