### ISSUE TITLE
Coverage metrics are not calculated over the whole codebase 

### ISSUE THREAD

**Issue by xross** [xmos/lib_xud#295]
Coverage metrics are only calculated over code that makes it into the application test binaries.  This means that one could achieve 100% coverage by simply not using large regions of code. This task includes two main components: 
- Coverage metrics should be calculated over all files in code base
- Coverage must be check on ASM files

**Comment by xross** [comment]
@kevinyeungxmos  first solution was to simply run all tests using -O0 hoping that symbols are not removed by optimisations - however, this may mean that tests do not pass at all. Also the mapper may still throw stuff away.

**Comment by xross** [comment]
@kevinyeungxmos, I took a look at the mapper options (xmap) it seems you can use the --retain option (Retain unreferenced objects). 

You can enable this by adding the following to the test_makefile.mak:

`-Xmapper --retain`

**Comment by kevinyeungxmos** [comment]
I got the following error when adding `-Xmapper --retain` to test_makefile.mak
/home/kevin/sandboxes/lib_xud_DEV_XS3/lib_xud/lib_xud/src/core/XUD_TestMode.S:(.text+0x34): Error: byte offset 0x00000032 for relocation R_XCORE1_REL16_4 is misaligned
/home/kevin/sandboxes/lib_xud_DEV_XS3/lib_xud/lib_xud/src/core/XUD_TestMode.S: Error: relocation with respect to 'InvalidTestToken'
/home/kevin/sandboxes/lib_xud_DEV_XS3/lib_xud/lib_xud/src/core/XUD_TestMode.S:(.text+0x40): Error: byte offset 0xffffffce for relocation R_XCORE1_REL16_4 is misaligned
/home/kevin/sandboxes/lib_xud_DEV_XS3/lib_xud/lib_xud/src/core/XUD_TestMode.S: Error: relocation with respect to 'XUD_UsbTestSE0_loop'
/home/kevin/sandboxes/lib_xud_DEV_XS3/lib_xud/lib_xud/src/core/XUD_TestMode.S:(.text+0x64): Error: byte offset 0xffffffaa for relocation R_XCORE1_REL16_4 is misaligned
/home/kevin/sandboxes/lib_xud_DEV_XS3/lib_xud/lib_xud/src/core/XUD_TestMode.S: Error: relocation with respect to 'XUD_UsbTestSE0_loop'
/home/kevin/sandboxes/lib_xud_DEV_XS3/lib_xud/lib_xud/src/core/XUD_TestMode.S:(.text+0x6c): Error: byte offset 0xfffffffa for relocation R_XCORE1_REL16_4 is misaligned
/home/kevin/sandboxes/lib_xud_DEV_XS3/lib_xud/lib_xud/src/core/XUD_TestMode.S: Error: relocation with respect to 'InvalidTestToken'
/home/kevin/sandboxes/lib_xud_DEV_XS3/lib_xud/lib_xud/src/core/XUD_TestMode.S:(.text+0x74): Error: byte offset 0xffffff9a for relocation R_XCORE1_REL16_4 is misaligned
/home/kevin/sandboxes/lib_xud_DEV_XS3/lib_xud/lib_xud/src/core/XUD_TestMode.S: Error: relocation with respect to 'XUD_UsbTestSE0_loop'

**Comment by kevinyeungxmos** [comment]
see #296
