### ISSUE TITLE
Some assembly files are still missing from the coverage report

### ISSUE THREAD

**Issue by xross** [xmos/lib_xud#307]
@kevinyeungxmos reports that xaddr2line returns a bad path

**Comment by kevinyeungxmos** [comment]
xaddr2line -p -f -e image_n0c0.elf 0x00082740
it returns:
XUD_IN_NotReady at /home/kevin/sandboxes/lib_xud_DEV_XS3/lib_xud/tests/test_bulk_rx_basic/.build_xs3_600_6_1_1_HS/./included/XUD_Token_In_DI.S:26

**Comment by xross** [comment]
Does moving the .S files from core/included to /core (and changing the #includes in XUD_IoLoop.S) help at all?

**Comment by kevinyeungxmos** [comment]
> Does moving the .S files from core/included to /core (and changing the #includes in XUD_IoLoop.S) help at all?
No, it doesn't work

**Comment by xross** [comment]
Looks like the ELF doesn't contain correct debug info for this #included files

**Comment by xross** [comment]
@kevinyeungxmos has added a workaround (search for correct path) in xmos/test_support

**Comment by xross** [comment]
In the elf/xe file the "working" files have the correct full path e.g:
/Users/ross/sandboxes/sb_xud_view/lib_xud/lib_xud/src/core/XUD_IoLoop.S

Whereas the included files just have the relative path e.g:
./included/XUD_Token_In_DI.S

**Comment by xross** [comment]
Internal issue raised with XMOS tools team - Bug #18615 (http://bugzilla/show_bug.cgi?id=18615)
