### ISSUE TITLE
module_build_info overwrite BUILD_FLAGS for some files out of lib_xud

### ISSUE THREAD

**Issue by fabriceo** [xmos/lib_xud#373]
hi,
module_build_info contains declaration for files included in lib_xua, out of the scope of lib_xud, and this creates an issue as the BUILD_FLAGS from the main Makefile is overwritten:
XCC_FLAGS_endpoint0.xc = $(MODULE_XCC_FLAGS) -Os
XCC_FLAGS_dfu.xc = $(MODULE_XCC_FLAGS) -Os
XCC_FLAGS_dfu_flash.xc = $(MODULE_XCC_FLAGS) -Os

**Comment by xross** [comment]
Fixed in #396 and #397
