### ISSUE TITLE
XS3A Test modes need validating

### ISSUE THREAD

**Issue by xross** [xmos/lib_xud#64]
The USB 2.0 Specification mandates Test Mode support (See 7.1.20 of the USB 2.0 Specification). These facilitate compliance testing and all high-speed capable devices must support them. These test modes are:
- Test_SE0_NAK
- Test_J
- Test_K
- Test_Packet

Test modes are entered via commands from the host using the USBHSETT tool (see https://www.usb.org/compliancetools)
All fours test modes have been implemented for XS3A. They have had some rough checking along with the levels.

**Comment by XMOS-JoeG** [comment]
For xs3, I have found the SE0_NAK test mode has an issue where the device never responds with NAK packets despite being given correct IN packets. Having had a look there is an error in the PID checking where we are using a register value that has been trampled over by the crc checking instructions. May also be an error in that we should respond (with NAK) to all addresses, not just the address we have been enumerated as.

**Comment by xross** [comment]
These have now been checked and an issue resolved https://github.com/xmos/lib_xud/pull/392
