### ISSUE TITLE
VBUS detect support required for XS3A

### ISSUE THREAD

**Issue by xross** [xmos/lib_xud#66]
No support for VBUS has been added (XS3A does not have a dedicated VBUS input pin). Some sort of callback and documentation should be added to use a regular I/O. ***This means that this library is not currently suitable for use with self powered devices***

**Comment by DaveAtkinsonXMOS** [comment]
I have implemented afunction XUD_GetVBusState() will get the state of the VBUS detection circuit. On the XS3 architecture it has weak linkage to allow it to be overridden with an application-specific version.

**Comment by DaveAtkinsonXMOS** [comment]
Issue completed.
