### ISSUE TITLE
Add infrastructural files to XS3 development

### ISSUE THREAD

**Issue by mbanth** [xmos/lib_xud#87]
The _DEV/XS3_ branch does not have the Jenkinsfile, Brewfile or requirements.txt files present.  It also does not have a python directory containing a setup.py file.  The _develop_ branch has all of these files and the python directory.  The infrastructural files on the two branches should be the same.

With the recent decision to separate python models from (what will become) publicly visible repositories, it may not be beneficial to keep the requirements.txt and setup.py files or the python directory.  Likewise, we may move away from using Brew altogether which will remove the need for a Brewfile.  At a minimum, either the Jenkinsfile should exist on both the _DEV/XS3_ branch and develop or the _DEV/XS3_ branch should be merged to _develop_, picking up the Jenkinsfile as a result.

**Comment by xross** [comment]
Setup.py needs to match requirements.txt then this can be closed.
