### ISSUE TITLE
XUD stops working as DFU after exceeding firmware size

### ISSUE THREAD

**Issue by mbanth** [xmos/lib_xud#92]
See [Awesome Support ticket 86700](https://www.xmos.ai/wp-admin/post.php?post=86700&action=edit).

**Comment by xross** [comment]
DFU is not handled by this library directly. 

Assuming a USB Audio project, a DFU with an image size greater than one supported with be truncated in the flash and not booted after a CRC check fail - the factory image with then be booted. No memory corruption will take place. 

Possibly the customer has some issue in their custom app handling DFU images.
