### ISSUE TITLE
USB3.0 compatibiliy issues

### ISSUE THREAD

**Issue by mbanth** [xmos/lib_xud#93]
See [Awesome Support ticket 87974](https://www.xmos.ai/wp-admin/post.php?post=87974&action=edit).  An interoperability problem may exist when connected to a USB 3.0 host device and that host device has the Thesycon 5.0 driver installed.  This issues does not arise when connected to a USB 2.0 or 3.1 port.

At this stage, it's not clear to me whether this issue applies to lib_xud or not.

**Comment by xross** [comment]
From customer after moving to lib_xud (from sc_xud):

`Everything is working fine on both my USB3.0 controllers that had issue with old USB module. No any issue anymore! Everything is 100% stable. You guys have made a fantastic job! You may close this case with solved mark.`

closing.
